### ISSUE TITLE
[configurable] Change binary configuration format to a text one

### ISSUE THREAD

**Issue by AudriusButkevicius** [phillipberndt/fakexrandr#12]
Because it's super hard to construct the configuration file from the command line, and the current utility does not have a CLI so I am bound to use the UI utility.

Furthermore, this would allow me to avoid having to use the configuration utility with all it's dependencies altogether, as installing GTK in a docker container is like to hell and back due to some dependencies relying on systemd rather than systemd-container.

**Comment by phillipberndt** [comment]
Fakexrandr has to load the configuration every time an application requests RandR information, which is at least once per startup of any X11 application using GTK or QT. That's why I prefer a file format that is easy to parse from C code and makes the configuration file as small as possible to minimize disk I/O.

Yet I see why having a CLI tool without the pygtk dependency would be beneficial. I'll look into that.
