### ISSUE TITLE
X session ends when running various xrandr commands / Add an option to set a primary output

### ISSUE THREAD

**Issue by lope** [phillipberndt/fakexrandr#15]
I have a script that I run to arrange my monitors and panels the way I like, depending if I have external screens connected, etc.

Any of the following commands cause the X session to end

```
$ xrandr --display :0 --output DP1~2 --mode 1920x1080
No protocol specified
Can't open display :0.0
$ xrandr --output DP1~2 --mode 1920x1080
$ xrandr --output DP1~2 --primary
```
Currently my primary monitor is VGA1, but I want DP1~2 to be primary.

I don't mind making my script communicate with the old xrandr to ensure the resolutions and positions are right, but then the problem is how can I tell the original Xrandr that DP1~2 is the primary monitor?

**Comment by phillipberndt** [comment]
Changing the configuration of fake outputs via xrandr does not work. (Since they are fake..); you'll have to use the original libXrandr.so to make any changes. X11 shouldn't exit though, I suspect that there's a bug in your WM, see https://github.com/phillipberndt/autorandr/pull/20 for a similar problem: xrandr might disable all outputs when you do the call and then fail because `DP1~2` does not exist, at least that's what happens here when I try to do this.

It would be possible to extend fakexrandr to also fake a primary output, via `XRRGetOutputPrimary`. But the necessary logic isn't clear to me right now.. if there are multiple real outputs in a configuration, the primary might be one of the fake screens or one that fakexrandr does not even know about. Might be best to do the mapping by name. Would this help you?

**Comment by lope** [comment]
Okay, can you please give an example of how to run a command on libXrandr.so ? (the real xrandr)

![image](https://cloud.githubusercontent.com/assets/2905035/8212802/23f2363a-151e-11e5-9571-b5ad90c0a375.png)

I'd like the center monitor to be primary.

Well in your interface maybe you could add a button that says "Select primary" and after you click that button, the primary monitor takes on a different appearance, or maybe just a confirmation msgbox.

**Comment by lope** [comment]
I must say, fakexrandr is pretty cool, I would not be surprised if it found it's way into xrandr somehow. I've not yet fully played around with splitting up my monitors, but I'm keen to try more. than just splitting by monitor.

**Comment by phillipberndt** [comment]
> Okay, can you please give an example of how to run a command on libXrandr.so ? (the real xrandr)

    LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/ xrandr

should work (the path is the one that `./configure` determined as the path to the real xrandr library, maybe it is different on your system)

**Comment by lope** [comment]
okay, when I search for xrandr, it is only found here:
```
/usr/share/bash-completion/completions/xrandr
/usr/bin/xrandr (fake)
```

```
./configure
XRandR version is 1.4.2
The path to the real XRandR library is /usr/local/lib/libXrandr.so.2
WARNING:  This looks as if you already have fakexrandr installed?!
          Using /usr/lib/x86_64-linux-gnu/libXrandr.so instead. (Found using `file')
The fake library will be installed to /usr/local/lib
./make_skeleton.py > skeleton.h || { rm -f skeleton.h; exit 1; }
cc -O2 -fPIC -shared -o libXrandr.so libXrandr.c
[ -e libXrandr.so.2 ] || ln -s libXrandr.so libXrandr.so.2
[ -e libXinerama.so.1 ] || ln -s libXrandr.so libXinerama.so.1

$ /usr/local/lib/libXrandr.so.2
Segmentation fault
```

**Comment by phillipberndt** [comment]
You'll have to enter the line

    LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/ xrandr

literally into your terminal.

**Comment by lope** [comment]
Great, thanks. This line gives me the real xrandr mate-display-properties
``LD_LIBRARY_PATH=/usr/lib/x86_64-linux-gnu/ mate-display-properties``
![image](https://cloud.githubusercontent.com/assets/2905035/8231225/5c67116c-15c7-11e5-84c4-16cdcf4ec045.png)
