### ISSUE TITLE
Uninstall

### ISSUE THREAD

**Issue by fgurel** [phillipberndt/fakexrandr#30]
How will I uninstall fakexrandr, it causes all of the windows to initially open in the splitted screen even though it is not primary and this messes a lot of things. But now I cannot uninstall it, sudo make uninstall gives error and stops. Any help?

Thank you

**Comment by nmschulte** [comment]
Paste the error from make.

**Comment by phillipberndt** [comment]
As a quick fix, search for all instances of libXrandr.so on your system.
Grep for _is_fake_xrandr. If the string is present, /rename/ the file (in
case you by accident still have the real one, renaming instead of deleting
allows to restore it). This should completely disable fakexrandr.

Nathan Schulte <notifications@github.com> schrieb am So., 15. Mai 2016,
00:45:

> Paste the error from make.

**Comment by fgurel** [comment]
Hi again,

When I use sudo make uninstall this is what I get;
TARGET_DIR=`sed -nre 's/#define FAKEXRANDR_INSTALL_DIR "([^"]+)"/\1/p' config.h`; \
	[ -d $TARGET_DIR ] || exit 1; \
	strings $TARGET_DIR/libXrandr.so | grep -q _is_fake_xrandr || exit 1; \
	rm -f $TARGET_DIR/libXrandr.so $TARGET_DIR/libXrandr.so.2 $TARGET_DIR/libXinerama.so.1 /usr/bin/fakexrandr-manage; \
	ldconfig
strings: '/usr/local/lib/libXrandr.so': No such file
make: *** [uninstall] Error 1

And I'll look into libXrandr right away; but actually if I could solve the first isssue there's no need to uninstall it anyway, that is the monitor that divided acts as the primary one and every application starts within it. Why would you consider this is happening? Thank you

**Comment by nmschulte** [comment]
Assuming you haven't re-configured the build since installing, I think that error message implies that fakexrandr is already uninstalled.
